import type { Tour } from "nextstepjs";

/**
 * Customer onboarding tour steps configuration
 * Guides new customers through the application features
 * 
 * Note: Steps that require navigation to different views should target
 * the view container IDs which are only visible when that view is active.
 */
export const customerOnboardingSteps: Tour[] = [
  {
    tour: "customerOnboarding",
    steps: [
      {
        icon: "👋",
        title: "Welcome!",
        content: "Welcome to Blackpepper Camp's Pizza! Let's take a quick tour to help you get started with ordering food.",
        // No selector - centered welcome message
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 0,
        pointerRadius: 0,
      },
      {
        icon: "🎉",
        title: "Promotional Banner",
        content: "Check here for special promotions, discounts, and limited-time offers. Swipe through multiple promotions if available!",
        selector: "#onboarding-promotion-banner",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "🔍",
        title: "Search Menu",
        content: "Use the search bar to quickly find your favorite dishes. Search by name or description to discover new items!",
        selector: "#onboarding-search-input",
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "📂",
        title: "Category Filter",
        content: "Browse menu items by category. You can select multiple categories and see other categories by swiping to the left.",
        selector: "#onboarding-category-filter",
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "🍕",
        title: "Menu Items",
        content: "Browse our delicious menu items. Click the '+' button on any item to add it to your cart and customize your order.",
        selector: "#onboarding-menu-grid",
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "🛒",
        title: "Your Cart",
        content: "Your cart shows all items you've added. Review quantities, see the total, and proceed to checkout when ready. Tap the cart icon in the top navigation to view your cart.",
        // Point to cart button in top nav (mobile) or desktop cart
        selector: "#onboarding-cart-mobile-button, #onboarding-cart-desktop",
        side: "bottom-right",
        showControls: true,
        showSkip: true,
        pointerPadding: 16,
        pointerRadius: 8,
      },
      {
        icon: "📋",
        title: "Navigation Menu",
        content: "Tap the menu icon in the top navigation to access the sidebar. The sidebar contains all the navigation options to explore different sections of the app.",
        // Point to burger menu button in top nav
        selector: "#onboarding-burger-menu-button",
        side: "bottom-left",
        showControls: true,
        showSkip: true,
        pointerPadding: 16,
        pointerRadius: 8,
      },
      {
        icon: "📋",
        title: "Navigation Sidebar",
        content: "This is the navigation sidebar. Use it to navigate through different sections like Pre-Orders, Active Orders, Order History, Inbox, Settings, and more. Let's explore the key features available to you.",
        // Target the sidebar container - ensure it's visible
        selector: "#onboarding-sidebar-menu",
        side: "right-top",
        showControls: true,
        showSkip: true,
        pointerPadding: 16,
        pointerRadius: 8,
      },
      {
        icon: "📅",
        title: "Pre-Orders",
        content: "Use Pre-Orders to view your scheduled orders. Click this to navigate to the Pre-Orders section.",
        selector: "#onboarding-nav-preorders",
        side: "bottom-right",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "⚡",
        title: "Active Orders",
        content: "Track your current orders here. See the status of orders that are being prepared or in transit. Click this button to navigate to Active Orders.",
        selector: "#onboarding-nav-activeorders",
        side: "right",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "📜",
        title: "Order History",
        content: "View all your past orders. Check order details, reorder favorite items, and track your ordering history. Click this button to navigate to Order History.",
        selector: "#onboarding-nav-orders",
        side: "right",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "💬",
        title: "Inbox",
        content: "Communicate with the restaurant about your orders. Send messages, ask questions, and receive updates here. Click this button to navigate to Inbox.",
        selector: "#onboarding-nav-inbox",
        side: "right",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "⚙️",
        title: "Settings",
        content: "Manage your profile, update your address, payment information, and preferences. You can also restart this tour from here! Click this button to navigate to Settings.",
        selector: "#onboarding-nav-settings",
        side: "right",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "📧",
        title: "Inquiry",
        content: "Have questions or feedback? Use the Inquiry section to contact the restaurant directly. Click this button to navigate to Inquiry.",
        selector: "#onboarding-nav-inquiry",
        side: "right",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "🏠",
        title: "Back to Menu",
        content: "Let's go back to the menu view. Click the Menu button in the sidebar to return to browsing items.",
        selector: "#onboarding-nav-menu",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 8,
      },
      {
        icon: "🎊",
        title: "You're All Set!",
        content: "That's everything you need to know! Start exploring and enjoy ordering delicious food. Happy ordering!",
        // No selector - centered completion message
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 0,
        pointerRadius: 0,
      },
    ],
  },
];
